name: carina-test
favicon: null
layout_spectrum: 0.932941934093833
typography_spectrum: 0.50271
title: Pondering projects
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e0e0'
    - '#000000'
    - '#9fa49e'
    - '#ad190e'
    - '#586d9f'
  brandStrength: 0.3991041425615549
  lightness: 0.625
  saturation: 0.167538417968899
  rhythmicContrast: 0.6849123612046242
purpose: []
